#!/usr/bin/env bash

set -e

HOSTNAME="$(hostname)"
CONFIG="install.conf.yaml"
HOSTCONFIG="install-${HOSTNAME}.conf.yaml"
DOTBOT_DIR="libs/git/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# If there is a config file for this host
if [ -f ${HOSTCONFIG} ]; then
	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${HOSTCONFIG}" "${@}"
fi
