[background]
# Path to the background image
path = "/usr/share/backgrounds/greeter.png"

# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
fit = "Contain"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Bibata-Modern-Ice"

# Font name and size
font_name = "Hack Nerd Font Mono 16"

# Icon theme name
icon_theme_name = "candy-icons"

# GTK theme name
theme_name = "Sweet"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
