#!/usr/bin/env zsh

# Zsh Configration

autoload -U compinit promptinit colors vcs_info
colors
compinit
promptinit

# Load zsh files
for i in $HOME/.config/zsh/*; do;
    test -r "$i" && source "$i"
done
